# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='crawl.Link')),
            ],
        ),
        migrations.CreateModel(
            name='UrlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256, null=True, unique=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='crawl.UrlList')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='crawl.WordList')),
            ],
        ),
        migrations.AddField(
            model_name='linkword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crawl.WordList'),
        ),
        migrations.AddField(
            model_name='link',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crawl.UrlList'),
        ),
        migrations.AddField(
            model_name='link',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='crawl.UrlList'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('source', 'to')]),
        ),
    ]
