# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlocation',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
