# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_auto_20161002_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='crawl.UrlList')),
            ],
        ),
    ]
