# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_pagerank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerank',
            name='score',
            field=models.FloatField(default=1.0),
        ),
    ]
